### ISSUE TITLE
请问这个问题怎么解决呢？

### ISSUE THREAD

**Issue by yuluzhong** [PaddlePaddle/PaddleCustomDevice#1454]
CMake Error at cmake/paddle.cmake:90 (message):
  Failed to get submodule Paddle', please check your network !
Call Stack (most recent call first):
  CMakeLists.txt:22 (include)

**Comment by yuluzhong** [comment]
请问我只能一个一个下载然后传到没有网的机器上吗？

**Comment by zbo2025** [comment]
你好这个问题怎么解决呢？
WARNING: Requirement 'build/dist/paddle_custom_npu*.whl' looks like a filename, but the file does not exist
ERROR: paddle_custom_npu*.whl is not a valid wheel filename.

**Comment by yuluzhong** [comment]
Traceback (most recent call last):
  File "/home/ma-user/work/PaddleCustomDevice/backends/npu/build/setup.py", line 140, in <module>
    main()
  File "/home/ma-user/work/PaddleCustomDevice/backends/npu/build/setup.py", line 99, in main
    write_custom_op_api_py()
  File "/home/ma-user/work/PaddleCustomDevice/backends/npu/build/setup.py", line 13, in write_custom_op_api_py
    op_names = paddle.utils.cpp_extension.extension_utils.load_op_meta_info_and_register_op(libname)
  File "/home/ma-user/anaconda3/envs/PyTorch-2.1.0/lib/python3.9/site-packages/paddle/utils/cpp_extension/extension_utils.py", line 162, in load_op_meta_info_and_register_op
    core.load_op_meta_info_and_register_op(lib_filename)
RuntimeError: (PreconditionNotMet) The third-party dynamic library (python/paddle_custom_device/libpaddle-custom-npu.so) that Paddle depends on is not configured correctly. (error code is python/paddle_custom_device/libpaddle-custom-npu.so: undefined symbol: _ZN13custom_kernel14GatherNdKernelIbN3phi13CustomContextEEEvRKT0_RKNS1_11DenseTensorES8_PS6_)
  Suggestions:
  1. Check if the third-party dynamic library (e.g. CUDA, CUDNN) is installed correctly and its version is matched with paddlepaddle you installed.
  2. Configure third-party dynamic library environment variables as follows:
  - Linux: set LD_LIBRARY_PATH by export LD_LIBRARY_PATH=...
  - Windows: set PATH by set PATH=XXX;%PATH%
  - Mac: set  DYLD_LIBRARY_PATH by export DYLD_LIBRARY_PATH=... [Note: After Mac OS 10.11, using the DYLD_LIBRARY_PATH is impossible unless System Integrity Protection (SIP) is disabled.] (at /paddle/paddle/phi/backends/dynload/dynamic_loader.cc:340)

make[2]: *** [CMakeFiles/python_package.dir/build.make:79: python/.timestamp] Error 1
make[1]: *** [CMakeFiles/Makefile2:345: CMakeFiles/python_package.dir/all] Error 2
make: *** [Makefile:101: all] Error 2
+ make_error=2
+ '[' 2 '!=' 0 ']'
+ echo 'Make Error Found !!!'
Make Error Found !!!
+ exit 7
这是什么错误，请问怎么解决呢？

**Comment by cmcamdy** [comment]
问题1: 如果机器没有网，确实只能这么干 
问题2: 看这个，ZN13custom_kernel14GatherNdKernelIbN3phi13CustomContextEEEvRKT0_RKNS1_11DenseTensorES8_PS6，这个函数没有实现（大概率是没链接到或者没实例化）

**Comment by yuluzhong** [comment]
> 问题1: 如果机器没有网，确实只能这么干 问题2: 看这个，ZN13custom_kernel14GatherNdKernelIbN3phi13CustomContextEEEvRKT0_RKNS1_11DenseTensorES8_PS6，这个函数没有实现（大概率是没链接到或者没实例化）

第二个问题该怎么解决呢？
