### ISSUE TITLE
NPU插件与sklearn存在兼容性问题

### ISSUE THREAD

**Issue by parap1uie-s** [PaddlePaddle/PaddleCustomDevice#374]
按照教程安装paddle与paddle_custom_device，如果先import paddle，再import sklearn，就会报错：
```
>>> import paddle
I0129 11:20:21.808104 11223 init.cc:266] ENV [CUSTOM_DEVICE_ROOT]=/opt/py37env/lib/python3.7/site-packages/paddle-plugins
I0129 11:20:21.808182 11223 init.cc:150] Try loading custom device libs from: [/opt/py37env/lib/python3.7/site-packages/paddle-plugins]
I0129 11:20:26.164170 11223 custom_device.cc:1040] Successed in loading custom runtime in lib: /opt/py37env/lib/python3.7/site-packages/paddle-plugins/libpaddle-custom-npu.so
I0129 11:20:26.169677 11223 custom_kernel.cc:76] Successed in loading 296 custom kernel(s) from loaded lib(s), will be used like native ones.
I0129 11:20:26.169983 11223 init.cc:162] Finished in LoadCustomDevice with libs_path: [/opt/py37env/lib/python3.7/site-packages/paddle-plugins]
I0129 11:20:26.170037 11223 init.cc:272] CustomDevice: npu, visible devices count: 8
>>> import sklearn
Traceback (most recent call last):
  File "/opt/py37env/lib/python3.7/site-packages/sklearn/__check_build/__init__.py", line 48, in <module>
    from ._check_build import check_build  # noqa
ImportError: /opt/py37env/lib/python3.7/site-packages/sklearn/__check_build/../../scikit_learn.libs/libgomp-d22c30c5.so.1.0.0: cannot allocate memory in static TLS block

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/opt/py37env/lib/python3.7/site-packages/sklearn/__init__.py", line 81, in <module>
    from . import __check_build  # noqa: F401
  File "/opt/py37env/lib/python3.7/site-packages/sklearn/__check_build/__init__.py", line 50, in <module>
    raise_build_error(e)
  File "/opt/py37env/lib/python3.7/site-packages/sklearn/__check_build/__init__.py", line 43, in raise_build_error
    % (e, local_dir, "".join(dir_content).strip(), msg)
ImportError: /opt/py37env/lib/python3.7/site-packages/sklearn/__check_build/../../scikit_learn.libs/libgomp-d22c30c5.so.1.0.0: cannot allocate memory in static TLS block
___________________________________________________________________________
Contents of /opt/py37env/lib/python3.7/site-packages/sklearn/__check_build:
setup.py                  __pycache__               _check_build.cpython-37m-aarch64-linux-gnu.so
__init__.py
___________________________________________________________________________
It seems that scikit-learn has not been built correctly.

If you have installed scikit-learn from source, please do not forget
to build the package before using it: run `python setup.py install` or
`make` in the source directory.

If you have used an installer, please check that it is suited for your
Python version, your operating system and your platform.
```

反之如果先import sklearn，则一切正常：
```
>>> import sklearn
>>> import paddle
I0129 11:20:43.997946 11705 init.cc:266] ENV [CUSTOM_DEVICE_ROOT]=/opt/py37env/lib/python3.7/site-packages/paddle-plugins
I0129 11:20:43.998006 11705 init.cc:150] Try loading custom device libs from: [/opt/py37env/lib/python3.7/site-packages/paddle-plugins]
I0129 11:20:48.402534 11705 custom_device.cc:1040] Successed in loading custom runtime in lib: /opt/py37env/lib/python3.7/site-packages/paddle-plugins/libpaddle-custom-npu.so
I0129 11:20:48.407981 11705 custom_kernel.cc:76] Successed in loading 296 custom kernel(s) from loaded lib(s), will be used like native ones.
I0129 11:20:48.408267 11705 init.cc:162] Finished in LoadCustomDevice with libs_path: [/opt/py37env/lib/python3.7/site-packages/paddle-plugins]
I0129 11:20:48.408321 11705 init.cc:272] CustomDevice: npu, visible devices count: 8
```

**Comment by qili93** [comment]
aarch64 环境与 sklearn 的问题，参考 https://github.com/PaddlePaddle/PaddleCustomDevice/blob/develop/backends/npu/tools/dockerfile/Dockerfile.npu.ubuntu18-aarch64-gcc82#L69 中的环境变量修复，建议尽量使用README中标准的开发镜像，参考 https://github.com/PaddlePaddle/PaddleCustomDevice/blob/develop/backends/npu/README_cn.md
