### ISSUE TITLE
paddle.jit.to_static fail with custom device

### ISSUE THREAD

**Issue by qili93** [PaddlePaddle/PaddleCustomDevice#42]
CustomDevice currently not support dygraph to static, reproduce steps as following.

1. Install `paddle-custom-npu` based on [README](https://github.com/PaddlePaddle/PaddleCustomDevice/blob/develop/backends/npu/README.md)

2. Run mnist_train.py on CPU succeeded:

```python
from __future__ import print_function

import os
import shutil
import numpy as np
import paddle
from paddle import nn
import paddle.nn.functional as F

class ConvBNLayer(nn.Layer):
    def __init__(self,
                 num_channels,
                 num_filters,
                 filter_size,
                 stride,
                 padding,
                 num_groups=1):
        super().__init__()

        self.conv = nn.Conv2D(
            in_channels=num_channels,
            out_channels=num_filters,
            kernel_size=filter_size,
            stride=stride,
            padding=padding,
            groups=num_groups,
            weight_attr=None,
            bias_attr=False)
        self.bn = nn.BatchNorm(num_filters)
        self.relu = nn.ReLU()

    def forward(self, x):
        x = self.conv(x)
        x = self.bn(x)
        x = self.relu(x)
        return x

class MNIST(nn.Layer):
    def __init__(self):
        super(MNIST, self).__init__()

        self.conv0 = ConvBNLayer(
                    num_channels=1,
                    num_filters=4,
                    filter_size=5,
                    stride=1,
                    padding=0,
                    num_groups=1)
        self.conv1 = ConvBNLayer(
                    num_channels=4,
                    num_filters=4,
                    filter_size=1,
                    stride=1,
                    padding=0,
                    num_groups=1)
        self.max_pool = nn.MaxPool2D(kernel_size=4, stride=4, padding=0)
        self.fc = nn.Linear(in_features=144, out_features=10)

    @paddle.jit.to_static()
    def forward(self, inputs, label=None):
        x = self.conv0(inputs)
        x1 = self.max_pool(x)
        x2 = self.conv1(x1)
        x = paddle.add(x=x1, y=x2)
        x = paddle.flatten(x, start_axis=1, stop_axis=-1)
        x = self.fc(x)
        out = F.softmax(x)
        if label is not None:
            acc = paddle.metric.accuracy(input=x, label=label)
            return out, acc
        else:
            return out

def test_mnist(test_reader, mnist_model):
    acc_set = []
    avg_loss_set = []

    for batch_id, data in enumerate(test_reader()):
        x_data = np.array([x[0].reshape(1, 28, 28) for x in data]).astype('float32')
        y_data = np.array([x[1] for x in data]).astype('int64').reshape(-1, 1)

        image = paddle.to_tensor(x_data)
        label = paddle.to_tensor(y_data)

        prediction, acc = mnist_model(image, label)
        loss = F.cross_entropy(input=prediction, label=label)
        avg_loss = paddle.mean(loss)

        acc_set.append(float(acc.numpy()))
        avg_loss_set.append(float(avg_loss.numpy()))

    acc_val_mean = np.array(acc_set).mean()
    avg_loss_val_mean = np.array(avg_loss_set).mean()
    return avg_loss_val_mean, acc_val_mean


def train_mnist(num_epochs, save_dirname):
    paddle.set_device('cpu')

    mnist = MNIST()
    adam = paddle.optimizer.Adam(learning_rate=0.001, parameters=mnist.parameters())

    train_reader = paddle.batch(paddle.dataset.mnist.train(), batch_size=BATCH_SIZE, drop_last=True)
    test_reader = paddle.batch(paddle.dataset.mnist.test(), batch_size=BATCH_SIZE, drop_last=True)

    for epoch in range(num_epochs):
        for batch_id, data in enumerate(train_reader()):
            x_data = np.array([x[0].reshape(1, 28, 28) for x in data]).astype('float32')
            y_data = np.array([x[1] for x in data]).astype('int64').reshape(-1, 1)

            image = paddle.to_tensor(x_data)
            label = paddle.to_tensor(y_data)

            cost, acc = mnist(image, label)
            loss = F.cross_entropy(cost, label)
            avg_loss = paddle.mean(loss)

            avg_loss.backward()
            adam.minimize(avg_loss)
            mnist.clear_gradients()

            if batch_id % 100 == 0:
                print("Loss at epoch {} step {}: {:}".format(epoch, batch_id, avg_loss.numpy()))

        mnist.eval()
        test_cost, test_acc = test_mnist(test_reader, mnist)
        mnist.train()
        print("Loss at epoch {} , Test avg_loss is: {}, acc is: {}".format(epoch, test_cost, test_acc))

    # save inference model
    if save_dirname is None:
        return
    # delete old model
    if  os.path.exists(save_dirname):
        shutil.rmtree(save_dirname)
        os.makedirs(save_dirname)
    # save inference model
    mnist.eval()
    model = paddle.jit.to_static(mnist, input_spec=[paddle.static.InputSpec([None, 1, 28, 28], 'float32', 'image')])
    paddle.jit.save(model, save_dirname)

if __name__ == '__main__':
    BATCH_SIZE = 64
    train_mnist(num_epochs=1, save_dirname='assets/mnist')
```

3. Change `paddle.set_device('cpu')` to `paddle.set_device('ascend')`, then fail with error as following:

```bash
(base) λ cann504 /workspace/my-demo-code/PaddlePaddle/mnistv2 {develop} python mnist_train.py
grep: warning: GREP_OPTIONS is deprecated; please use an alias or script
I0618 05:08:42.379591 88034 init.cc:259] ENV [CUSTOM_DEVICE_ROOT]=/opt/conda/lib/python3.7/site-packages/paddle-plugins
I0618 05:08:42.379639 88034 init.cc:147] Try loading custom device libs from: [/opt/conda/lib/python3.7/site-packages/paddle-plugins]
I0618 05:08:42.832442 88034 custom_device.cc:712] Successed in loading custom runtime in lib: /opt/conda/lib/python3.7/site-packages/paddle-plugins/libpaddle-custom-npu.so
I0618 05:08:42.834924 88034 custom_kernel.cc:70] Successed in loading 123 custom kernel(s) from loaded lib(s), will be used like native ones.
I0618 05:08:42.835026 88034 init.cc:159] Finished in LoadCustomDevice with libs_path: [/opt/conda/lib/python3.7/site-packages/paddle-plugins]
I0618 05:08:42.835060 88034 init.cc:265] CustomDevice: ascend, visible devices count: 1
Traceback (most recent call last):
  File "/opt/conda/lib/python3.7/site-packages/paddle/fluid/dygraph/dygraph_to_static/program_translator.py", line 379, in __call__
    return partial_program_layer(args)
  File "/opt/conda/lib/python3.7/site-packages/paddle/fluid/dygraph/dygraph_to_static/partial_program.py", line 349, in __call__
    in_vars, out_vars = self._prepare(inputs)
  File "/opt/conda/lib/python3.7/site-packages/paddle/fluid/dygraph/dygraph_to_static/partial_program.py", line 443, in _prepare
    expected_place):
TypeError: _equals(): incompatible function arguments. The following argument types are supported:
    1. (self: paddle.fluid.core_avx.Place, arg0: paddle.fluid.core_avx.Place) -> bool
    2. (self: paddle.fluid.core_avx.Place, arg0: paddle.fluid.core_avx.CUDAPlace) -> bool
    3. (self: paddle.fluid.core_avx.Place, arg0: paddle.fluid.core_avx.CPUPlace) -> bool
    4. (self: paddle.fluid.core_avx.Place, arg0: paddle.fluid.core_avx.XPUPlace) -> bool
    5. (self: paddle.fluid.core_avx.Place, arg0: paddle.fluid.core_avx.NPUPlace) -> bool
    6. (self: paddle.fluid.core_avx.Place, arg0: paddle.fluid.core_avx.IPUPlace) -> bool
    7. (self: paddle.fluid.core_avx.Place, arg0: paddle.fluid.core_avx.CUDAPinnedPlace) -> bool
    8. (self: paddle.fluid.core_avx.Place, arg0: paddle.fluid.core_avx.MLUPlace) -> bool

Invoked with: Place(ascend:0), Place(ascend:0)

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "mnist_train.py", line 158, in <module>
    train_mnist(num_epochs=1, save_dirname='assets/mnist')
  File "mnist_train.py", line 128, in train_mnist
    cost, acc = mnist(image, label)
  File "/opt/conda/lib/python3.7/site-packages/paddle/fluid/dygraph/layers.py", line 929, in __call__
    return self._dygraph_call_func(*inputs, **kwargs)
  File "/opt/conda/lib/python3.7/site-packages/paddle/fluid/dygraph/layers.py", line 914, in _dygraph_call_func
    outputs = self.forward(*inputs, **kwargs)
  File "/opt/conda/lib/python3.7/site-packages/paddle/fluid/dygraph/dygraph_to_static/program_translator.py", line 388, in __call__
    error_data.raise_new_exception()
  File "/opt/conda/lib/python3.7/site-packages/paddle/fluid/dygraph/dygraph_to_static/error.py", line 328, in raise_new_exception
    new_exception = self.create_exception()
  File "/opt/conda/lib/python3.7/site-packages/paddle/fluid/dygraph/dygraph_to_static/error.py", line 161, in create_exception
    message = self.create_message()
  File "/opt/conda/lib/python3.7/site-packages/paddle/fluid/dygraph/dygraph_to_static/error.py", line 182, in create_message
    self._simplify_error_value()
  File "/opt/conda/lib/python3.7/site-packages/paddle/fluid/dygraph/dygraph_to_static/error.py", line 267, in _simplify_error_value
    start_idx = error_value_lines_strip.index(start_trace)
ValueError: 'outputs = static_func(*inputs)' is not in list
```

**Comment by qili93** [comment]
https://github.com/PaddlePaddle/PaddleCustomDevice/blob/develop/backends/npu/tests/test_MNIST_model.py not work even with CPU place with git diff below

```bash
(base) λ cann504 /workspace/PaddleCustomDevice/backends/npu {develop} git diff tests/test_MNIST_model.py
diff --git a/backends/npu/tests/test_MNIST_model.py b/backends/npu/tests/test_MNIST_model.py
index b807093..d6361b7 100644
--- a/backends/npu/tests/test_MNIST_model.py
+++ b/backends/npu/tests/test_MNIST_model.py
@@ -50,6 +50,7 @@ class MNIST(paddle.nn.Layer):
         self.output_weight = self.create_parameter([self.shape, self.size])
         self.accuracy = paddle.metric.Accuracy()

+    @paddle.jit.to_static()
     def forward(self, inputs, label=None):
         x = paddle.reshape(inputs, shape=[-1, self.shape])
         x = paddle.matmul(x, self.output_weight)
@@ -64,7 +65,7 @@ class MNIST(paddle.nn.Layer):
             return x


-paddle.set_device('ascend')
+paddle.set_device('cpu')
 mnist = MNIST()
 adam = Adam(learning_rate=0.001, parameters=mnist.parameters())

@@ -83,5 +84,6 @@ for epoch in range(epoch_num):
         if batch_id % 100 == 0:
             print("Epoch {} step {}, Loss = {:}, Accuracy = {:}".format(
                 epoch, batch_id, avg_loss.numpy(), acc))
-model_dict = mnist.state_dict()
-paddle.save(model_dict, "mnist.pdparams")
+mnist.eval()
+model = paddle.jit.to_static(mnist, input_spec=[paddle.static.InputSpec([None, 1, 28, 28], 'float32', 'image')])
+paddle.jit.save(model, 'assets/mnist')
```

**Comment by Aganlengzi** [comment]
In PaddlePaddle, `to_static` depends on ParallelExecutor, both NPU and CustomDevice not support ParallelExecutor now,
so, we can not use `to_static` now and will be supported later.

test_MNIST_model.py is modified to support `to_static` for CPU in https://github.com/PaddlePaddle/PaddleCustomDevice/pull/43

**Comment by ronny1996** [comment]
dy2static add custom device support in https://github.com/PaddlePaddle/Paddle/pull/45878
