### ISSUE TITLE
[intel_gpu] elementwise_sub op unittest failed

### ISSUE THREAD

**Issue by ChengleiTian** [PaddlePaddle/PaddleCustomDevice#599]
我把mlu目录下的test_elementwise_sub_op_mlu.py测试脚本移植到intel_gpu来，在以下几个测试用例中报错：
1 TestElementwiseSubOp_broadcast_4
2 TestElementwiseSubOp_commonuse_1
3 TestElementwiseSubOp_commonuse_2
报错的原因都是类似的，TestElementwiseSubOp_broadcast_4的错误信息如下：
======================================================================
ERROR: test_check_grad_ingore_x (_main_.TestElementwiseSubOp_broadcast_4)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "test_elementwise_sub_op_intel_gpu.py", line 65, in test_check_grad_ingore_x
    self.place, ["Y"], "Out", max_relative_error=0.005, no_grad_set=set("X")
  File "/home/tcl/master/frameworks.ai.paddle.gpu/python/tests/op_test.py", line 2517, in check_grad_with_place
    atol=atol,
  File "/home/tcl/master/frameworks.ai.paddle.gpu/python/tests/op_test.py", line 2250, in _assert_is_close
    diff_mat = np.abs(a - b) / abs_a
ValueError: operands could not be broadcast together with shapes (2,5,1,12) (2,5,12)

======================================================================
ERROR: test_check_grad_normal (_main_.TestElementwiseSubOp_broadcast_4)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "test_elementwise_sub_op_intel_gpu.py", line 61, in test_check_grad_normal
    self.check_grad_with_place(self.place, ["X", "Y"], "Out")
  File "/home/tcl/master/frameworks.ai.paddle.gpu/python/tests/op_test.py", line 2517, in check_grad_with_place
    atol=atol,
  File "/home/tcl/master/frameworks.ai.paddle.gpu/python/tests/op_test.py", line 2250, in _assert_is_close
    diff_mat = np.abs(a - b) / abs_a
ValueError: operands could not be broadcast together with shapes (2,5,1,12) (2,5,12)

----------------------------------------------------------------------

**Comment by qili93** [comment]
您好， (2,5,1,12) (2,5,12) 这两个shape不符合tensor的广播机制因此报错，可以参考 https://www.paddlepaddle.org.cn/documentation/docs/zh/develop/guides/beginner/tensor_cn.html#id7 。

应该需要将 (2,5,12) 改为 (2,5,12,1) 之后2个tensor的shape就可以广播了，可以检查下 (2,5,12) 的shape是否设置错误。

**Comment by qili93** [comment]
您好，请问这个问题是否已经解决，谢谢！

**Comment by qili93** [comment]
Close as no more comments for more then two weeks, please reopen if not resolved, thanks!
