### ISSUE TITLE
The kernel with key (npu, Undefined(AnyLayout), float16) of kernel `silu` is not registered and fail to fallback to CPU one

### ISSUE THREAD

**Issue by Daniel-deng-yi** [PaddlePaddle/PaddleCustomDevice#615]
在Ascend910 npu环境上训练，训练时加载数据后出现以下错误
![image](https://github.com/PaddlePaddle/PaddleCustomDevice/assets/61072437/96d4ff61-133e-4695-9807-5e6ff77191b7)

[06/07 17:19:37] ppdet.data.source.coco INFO: Load [100625 samples valid, 0 samples invalid] in file /cache/train.json.
Traceback (most recent call last):
  File "/home/ma-user/work/01.paddle_npu_20230603/01.PaddleYOLO-release-2.5-init/train.py", line 188, in <module>
    main()
  File "/home/ma-user/work/01.paddle_npu_20230603/01.PaddleYOLO-release-2.5-init/train.py", line 184, in main
    run(FLAGS, cfg)
  File "/home/ma-user/work/01.paddle_npu_20230603/01.PaddleYOLO-release-2.5-init/train.py", line 137, in run
    trainer.train(FLAGS.eval)
  File "/home/ma-user/work/01.paddle_npu_20230603/01.PaddleYOLO-release-2.5-init/ppdet/engine/trainer.py", line 414, in train
    outputs = model(data)
  File "/home/ma-user/anaconda3/envs/TensorFlow-1.15.0/lib/python3.7/site-packages/paddle/nn/layer/layers.py", line 1254, in __call__
    return self.forward(*inputs, **kwargs)
  File "/home/ma-user/work/01.paddle_npu_20230603/01.PaddleYOLO-release-2.5-init/ppdet/modeling/architectures/meta_arch.py", line 59, in forward
    out = self.get_loss()
  File "/home/ma-user/work/01.paddle_npu_20230603/01.PaddleYOLO-release-2.5-init/ppdet/modeling/architectures/yolov7.py", line 95, in get_loss
    return self._forward()
  File "/home/ma-user/work/01.paddle_npu_20230603/01.PaddleYOLO-release-2.5-init/ppdet/modeling/architectures/yolov7.py", line 73, in _forward
    body_feats = self.backbone(self.inputs)
  File "/home/ma-user/anaconda3/envs/TensorFlow-1.15.0/lib/python3.7/site-packages/paddle/nn/layer/layers.py", line 1254, in __call__
    return self.forward(*inputs, **kwargs)
  File "/home/ma-user/work/01.paddle_npu_20230603/01.PaddleYOLO-release-2.5-init/ppdet/modeling/backbones/yolov7_elannet.py", line 592, in forward
    x = self.stem(x)
  File "/home/ma-user/anaconda3/envs/TensorFlow-1.15.0/lib/python3.7/site-packages/paddle/nn/layer/layers.py", line 1254, in __call__
    return self.forward(*inputs, **kwargs)
  File "/home/ma-user/anaconda3/envs/TensorFlow-1.15.0/lib/python3.7/site-packages/paddle/nn/layer/container.py", line 606, in forward
    input = layer(input)
  File "/home/ma-user/anaconda3/envs/TensorFlow-1.15.0/lib/python3.7/site-packages/paddle/nn/layer/layers.py", line 1254, in __call__
    return self.forward(*inputs, **kwargs)
  File "/home/ma-user/work/01.paddle_npu_20230603/01.PaddleYOLO-release-2.5-init/ppdet/modeling/backbones/csp_darknet.py", line 87, in forward
    y = self.act(x)
  File "/home/ma-user/anaconda3/envs/TensorFlow-1.15.0/lib/python3.7/site-packages/paddle/nn/layer/layers.py", line 1254, in __call__
    return self.forward(*inputs, **kwargs)
  File "/home/ma-user/anaconda3/envs/TensorFlow-1.15.0/lib/python3.7/site-packages/paddle/nn/layer/activation.py", line 1163, in forward
    return F.silu(x, self._name)
  File "/home/ma-user/anaconda3/envs/TensorFlow-1.15.0/lib/python3.7/site-packages/paddle/nn/functional/activation.py", line 985, in silu
    return _C_ops.silu(x)
RuntimeError: (NotFound) The kernel with key (npu, Undefined(AnyLayout), float16) of kernel `silu` is not registered and fail to fallback to CPU one. Selected wrong Backend `npu`. Paddle support following Backends: CPU.
  [Hint: Expected kernel_iter != iter->second.end(), but received kernel_iter == iter->second.end().] (at /paddle/paddle/phi/core/kernel_factory.cc:259)

**Comment by onecatcn** [comment]
silu确实不支持的哈，通常PaddleCustomDevice/backends/npu/kernel中不存在对应kernel就是不支持的。
fail to fall back to cpu需要请 @YanhuiDua 帮忙看一下

**Comment by Daniel-deng-yi** [comment]
> silu确实不支持的哈，通常PaddleCustomDevice/backends/npu/kernel中不存在对应kernel就是不支持的。 fail to fall back to cpu需要请 @YanhuiDua 帮忙看一下

我想知道哪一个激活函数可以替换在npu上使用

**Comment by YanhuiDua** [comment]
你好，目前npu上不支持silu op，由于这里是fp16类型，无法fallback搭配cpu执行；
可以用swish替换，定义见https://www.paddlepaddle.org.cn/documentation/docs/zh/api/paddle/nn/functional/swish_cn.html#swish
