### ISSUE TITLE
[NPU] 单机多卡分布式训练提示RuntimeError: (NotFound) The kernel `sync_batch_norm` is not registered.

### ISSUE THREAD

**Issue by 535205856** [PaddlePaddle/PaddleCustomDevice#694]
单机多卡报错
python -m paddle.distributed.fleet.launch --run_mode=collective --npus="4,5,6,7"  tools/train.py -c configs/yolov3/yolov3_darknet53_270e_roadsign.yml  -o use_npu=True

单机单卡可以训练

------------------------------------
宿主机机器环境是 昇腾910npu + 鲲鹏920 arm cpu 的 ubuntu 环境
镜像使用是npu文档中的镜像 registry.baidubce.com/device/paddle-npu:cann601-ubuntu18-aarch64-gcc82
------------------------------------
训练异常报错，

Traceback (most recent call last):
  File "tools/train.py", line 205, in <module>
    main()
  File "tools/train.py", line 201, in main
    run(FLAGS, cfg)
  File "tools/train.py", line 151, in run
    trainer.train(FLAGS.eval)
  File "/workspace/PaddleDetection/ppdet/engine/trainer.py", line 539, in train
    outputs = model(data)
  File "/opt/py37env/lib/python3.7/site-packages/paddle/nn/layer/layers.py", line 1253, in __call__
    return self.forward(*inputs, **kwargs)
  File "/opt/py37env/lib/python3.7/site-packages/paddle/distributed/parallel.py", line 534, in forward
    outputs = self._layers(*inputs, **kwargs)
  File "/opt/py37env/lib/python3.7/site-packages/paddle/nn/layer/layers.py", line 1253, in __call__
    return self.forward(*inputs, **kwargs)
  File "/workspace/PaddleDetection/ppdet/modeling/architectures/meta_arch.py", line 60, in forward
    out = self.get_loss()
  File "/workspace/PaddleDetection/ppdet/modeling/architectures/yolo.py", line 147, in get_loss
    return self._forward()
  File "/workspace/PaddleDetection/ppdet/modeling/architectures/yolo.py", line 81, in _forward
    body_feats = self.backbone(self.inputs)
  File "/opt/py37env/lib/python3.7/site-packages/paddle/nn/layer/layers.py", line 1253, in __call__
    return self.forward(*inputs, **kwargs)
  File "/workspace/PaddleDetection/ppdet/modeling/backbones/darknet.py", line 330, in forward
    out = self.conv0(x)
  File "/opt/py37env/lib/python3.7/site-packages/paddle/nn/layer/layers.py", line 1253, in __call__
    return self.forward(*inputs, **kwargs)
  File "/workspace/PaddleDetection/ppdet/modeling/backbones/darknet.py", line 77, in forward
    out = self.batch_norm(out)
  File "/opt/py37env/lib/python3.7/site-packages/paddle/nn/layer/layers.py", line 1253, in __call__
    return self.forward(*inputs, **kwargs)
  File "/opt/py37env/lib/python3.7/site-packages/paddle/nn/layer/norm.py", line 1557, in forward
    False,
RuntimeError: (NotFound) The kernel `sync_batch_norm` is not registered.
  [Hint: Expected iter != kernels_.end(), but received iter == kernels_.end().] (at /paddle/paddle/phi/core/kernel_factory.cc:219)

**Comment by YanhuiDua** [comment]
目前npu不支持sync_bn算子，需要替换为普通的bn算子；

请问paddledetection用的是什么版本呢？https://github.com/PaddlePaddle/PaddleDetection/pull/8247 这个PR已经修改为设备为npu时sync_bn为false，可以参考修改下

**Comment by 535205856** [comment]
> 目前npu不支持sync_bn算子，需要替换为普通的bn算子；
> 
> 请问paddledetection用的是什么版本呢？[PaddlePaddle/PaddleDetection#8247](https://github.com/PaddlePaddle/PaddleDetection/pull/8247) 这个PR已经修改为设备为npu时sync_bn为false，可以参考修改下

使用的是paddleDetection v2.6.0, 这个tag下的没有改，在release/2.6 下面是改了的，没想到这两个还不一样，想问问paddlepaddle 的各个子类包detection检测,seg分割,clas分类，等类型对npu的支持到什么地步了，里面的网络模型的算子都是支持npu吗，性能都是如何的，其中哪些网络模型是确定支持上没问题的，有没有哪里能详细看到这样的报告或者说明的

**Comment by YanhuiDua** [comment]
> 

你好，paddle-npu对detection/seg/clas模型的精度/算子/性能支持的情况，请通过官网：https://www.paddlepaddle.org.cn/install/other?docurl=/documentation/docs/zh/install/pip/linux-pip.html 的渠道来获取，谢谢

**Comment by YanhuiDua** [comment]
你好，没有其他问题的话，这个issue先关闭了，有问题欢迎再提出issue
